### PR TITLE
Tests for objectToPremisEventXML.

### LINKED ISSUE #27: Tests for the presentation module
Add tests for functions defined in `premis_event_service/presentation.py`

### PR DESCRIPTION
**Pull request by damonkelley**
Partially resolves #27

### CODE REVIEW

**Comment by damonkelley** [comment]
ping @ldko @somexpert

**Comment by somexpert** [comment]
:+1:

**Comment by ldko** [comment]
Should we test the linkObjectIDRoleXML even though we don't tend to use it?

**Comment by damonkelley** [comment]
@ldko added in bf4a93f

**Comment by ldko** [comment]
:+1:

**Pull request merged**
