### PR TITLE
Fix inconsistent references to request parameter for linked object id

### LINKED ISSUE #82: Problems with event/search/ and linked_object_id
`event/search/?linked_object_id=someid` throws a 500 error if you pass a `linked_object_id` that does not exist when the "someid" looks like `codae9e` rather than `ark:/67531/codae9e`.

when `event/search/?linked_object_id=someid` has multiple pages of results, the pagination links get an empty `linked_object_id` value (such as `event/search/?page=2&event_outcome=&event_type=&start_date=&end_date=&linked_object_id=&min_ordinal=204373`) so you get a bunch of unassociated results on the events search pages after the first one.

### PR DESCRIPTION
**Pull request by runderwood**
This should close #82.

Also refs. https://github.com/unt-libraries/coda/pull/111

@ldko @somexpert

### CODE REVIEW

**Comment by somexpert** [comment]
Quick question: how do you feel about removing the step from the slice in the changed code? Seems superfluous, but either way, LGTM :thumbsup:

**Comment by runderwood** [comment]
@somexpert The step is there to force queryset evaluation, I believe (see the comment above it). Otherwise, yes, I'd be happy to drop it. :grimacing:

**Comment by somexpert** [comment]
Ignore the guy who didn't read the comment above the code.

**Comment by runderwood** [comment]
It's a pretty weird deal. :ok_man:

**Pull request merged**
