### PR TITLE
update installation docs

### PR DESCRIPTION
**Pull request by runderwood**
@ldko @somexpert Updates the installation instructions to point to the latest release rather than `pypi` (since the app isn't hosted there).

### CODE REVIEW

**Comment by mchoeti** [comment]
I am also not sure if this instructions are enough, or valid

```
urlpatterns = [
    url(r'', include('premis_event_service.urls'))
    # ...
    url(r'^admin/', include(admin.site.urls)),
]
```

because normally a line has to be added  like this:
`from django.conf.urls import include`

but adding this:
` url(r'^admin/', include(admin.site.urls)),`

results to that
```
 File "/opt/chris/chris/urls.py", line 26, in <module>
    url(r'', include('premis_event_service.urls'))
```

**Comment by runderwood** [comment]
@mchoeti It's hard to say what's up without the full stack trace. Did you import `admin` in `urls.py` like this?

    from django.contrib import admin

It's true you do need to import `url` and `include` from the django url configuration module:

    from django.conf.urls import url, include

I think the docs just assume that's already the case, but it might make sense to make a note about it for clarity.

Can you confirm that you've imported `admin` as in the line above? If that's not the problem, could you post the full stack trace?

**Comment by mchoeti** [comment]
Hi, sure no problem this is the config file in the urls.py

```
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('premis_event_service.urls'))
    url(r'^admin/', include(admin.site.urls)),
]
```

And this is the stacktrace:
```
root@localhost chris]# python manage.py runserver 0.0.0.0:8000
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x32760c8>
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/lib64/python2.7/site-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/lib64/python2.7/site-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/lib64/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/lib64/python2.7/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/lib64/python2.7/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/lib64/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib64/python2.7/site-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/lib64/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib64/python2.7/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/chris/chris/urls.py", line 27
    url(r'^admin/', include(admin.site.urls)),
      ^
SyntaxError: invalid syntax
```
i see the errors, but i am only referencing to the docs..
i am also sure that real develpoper know how to solve that problem. But the case is how to build and use it from scratch.. but if you can give me some help, we might find out what the problem is and help so further users to resolve the problem

**Comment by runderwood** [comment]
@mchoeti You're missing a `,` after this line:

        url(r'', include('premis_event_service.urls'))

**Comment by runderwood** [comment]
@somexpert ping.

**Comment by somexpert** [comment]
looks good! :thumbsup:

**Comment by mchoeti** [comment]
@runderwood well i did that before, i was just refering to the doc


Here is the stacktrace:

```
Unhandled exception in thread started by <function wrapper at 0x19570c8>
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/lib64/python2.7/site-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/lib64/python2.7/site-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/lib64/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/lib64/python2.7/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/lib64/python2.7/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/lib64/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib64/python2.7/site-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/lib64/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib64/python2.7/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/chris/chris/urls.py", line 26, in <module>
    url(r'', include('premis_event_service.urls')),
  File "/usr/lib64/python2.7/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/premis_event_service/urls.py", line 2, in <module>
    from . import views
  File "/usr/lib/python2.7/site-packages/premis_event_service/views.py", line 31, in <module>
    MAINTENANCE_MSG = settings.MAINTENANCE_MSG
  File "/usr/lib64/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'MAINTENANCE_MSG'

```

**Comment by runderwood** [comment]
@mchoeti The only way I can see this happening is if you've changed the `tests/settings.py` file so that it's missing this line:

    MAINTENANCE_MESSAGE = None

Can you clarify how you're running `manage.py` (or, if you're doing this in the Docker container, how you're running it)?

**Comment by mchoeti** [comment]
hi, thanks for all the tips. i really did that step by step and following all the single steps, which means no Docker container. Based on your [documentation](http://premis-event-service.readthedocs.io/en/latest/installation.html#install) i fllowed the installation guide and fullfilled the requirements . Before i did a quick check with Django and was able to run on 
` python manage.py runserver 0.0.0.0:8000`

After adding the lines i came until step 5.  `python manage.py migrate` and got the stacktrace below:
It took me a while...  But now i came over with the solution and did the migration.. yes  :-)
After starting Django i receive this when i open up my page

```
Using the URL conf defined in chris.urls, Django tried these URL patterns, in this order:
^admin/
^APP/$ [name='app']
^APP/event/$ [name='app-event']
^APP/event/(?P<identifier>.+?)/$ [name='app-event-detail']
^APP/agent/$ [name='app-agent']
^APP/agent/(?P<identifier>.+?)/$ [name='app-agent-detail']
^event/$ [name='event-list']
^event/search/$ [name='event-search']
^event/search.json$ [name='event-search-json']
^event/find/(?P<linked_identifier>.+?)/(?P<event_type>.+?)?/$ [name='find-event']
^event/(?P<identifier>.+?)/$ [name='event-detail']
^agent/$ [name='agent-list']
^agent/(?P<identifier>.+?).xml$ [name='agent-detail-xml']
^agent/(?P<identifier>.+?).premis.xml$ [name='agent-detail-premis-xml']
^agent/(?P<identifier>.+?).json$ [name='agent-detail-json']
^agent/(?P<identifier>.+?)/$ [name='agent-detail']
^admin/
The current URL, , didn't match any of these.

```

I am getting closer but i am not sure if i can solve this. I still think there is something wrong with the urlpatterns. Because the configuration for my url file is:

```
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('premis_event_service.urls')),
    url(r'^admin/', include(admin.site.urls)),
]
```
So what do i miss ? I followed the instructions. On the weekend i will give docker a try. In the meantime do you have an idea why this is not working, or where the problem is?

**Comment by runderwood** [comment]
@mchoeti You're all set, I think. Just go to:

http://localhost:8000/event/

**Comment by mchoeti** [comment]
@runderwood not really, but no problem i will figure that out.. somewhere..  :-)  btw. i think there is something in the views.py or with the admin page, because i am getting an error to this 
[](http://localhost:8000/admin )or [](http://localhost:8000/event/  the ) 
```
TypeError at /event/
render_to_response() got an unexpected keyword argument 'context_instance'
Request Method:	GET
Request URL:	http://localhost:8000/event/

Django Version:	1.10.6
Exception Type:	TypeError
Exception Value:	render_to_response() got an unexpected keyword argument 'context_instance'
Exception Location:	/usr/lib/python2.7/site-packages/premis_event_service/views.py in recent_event_list, line 361
Python Executable:	/usr/bin/python
Python Version:	2.7.5
Python Path:	['/opt/chris',
'/usr/lib64/python27.zip',
'/usr/lib64/python2.7',
'/usr/lib64/python2.7/plat-linux2',
'/usr/lib64/python2.7/lib-tk',
'/usr/lib64/python2.7/lib-old',
'/usr/lib64/python2.7/lib-dynload',
'/usr/lib64/python2.7/site-packages',
'/usr/lib/python2.7/site-packages']
Server time:	Fri, 24 Mar 2017 11:08:24 +0000
```

All the best and, hey it`s weekend. Thanks for the help

**Comment by runderwood** [comment]
@mchoeti The problem is that you are using Django 1.10. I've pushed a new release of the app that is compatible with Django 1.10, so you should use [that version](https://github.com/unt-libraries/django-premis-event-service/releases/tag/v1.2.2) (1.2.2) instead of the previous one (1.2.1).

**Comment by mchoeti** [comment]
@runderwood thanks for taking care of that. in the meantime i succeeded to use the docker container. thantks for that. i will give feedback to the new version on monday. then i will submit all the installation notes, that you can update the installation guideline. hope thats ok, cheers mchoeti

**Pull request merged**
