### PR TITLE
Dev Env

### PR DESCRIPTION
**Pull request by damonkelley**
This adds a development environment to allow us to work on this project without putting it into a dummy Django project. 

All one needs is Docker and Compose. Once those requirements are satisfied, they can begin developing with a single command.

Also did a few housekeeping things with the requirements files.

All in all:
* Add Tox config
* Add Travis CI config
* Add Dockerfile
* Add Compose config
* Adds a test project
* Update the README with development information.

### CODE REVIEW

**Comment by damonkelley** [comment]
ping @somexpert @ldko

**Comment by somexpert** [comment]
:thumbsup:

**Comment by ldko** [comment]
Damon Kelley should be added to the Acknowledgements section of README

**Comment by damonkelley** [comment]
`Damon Kelley` added to the Acknowledgements section

**Comment by ldko** [comment]
:+1:

**Pull request merged**
