### PR TITLE
Replace the coda package with codalib

### LINKED ISSUE #18: Use codalib
Replace the `coda` package with unt-libraries/codalib.

### PR DESCRIPTION
**Pull request by damonkelley**
Resolves #18

### CODE REVIEW

**Comment by damonkelley** [comment]
I am going to hold off getting this reviewed until we have sufficient test coverage.

**Comment by damonkelley** [comment]
This will be ready one #40 and #42 are merged

**Comment by damonkelley** [comment]
ping @ldko @somexpert for after you review #42

**Comment by somexpert** [comment]
:+1:

**Comment by ldko** [comment]
:+1:

**Pull request merged**
