### PR TITLE
Consolidate the test settings.

### PR DESCRIPTION
**Pull request by damonkelley**
We don't need multiple settings files anymore. By default, Django will use an in-memory database when running the tests when the database engine is sqlite.

### CODE REVIEW

**Comment by damonkelley** [comment]
ping @somexpert @ldko

**Comment by somexpert** [comment]
Don't you also need to change manage.py?

**Comment by damonkelley** [comment]
good catch

**Comment by somexpert** [comment]
:thumbsup:

**Comment by ldko** [comment]
:+1:

**Pull request merged**
