### PR TITLE
Remove helpy and populator.

### LINKED ISSUE #19: Remove Unused Modules
The following modules are not used and can be removed

- `premis_event_service/helpy.py`
- `premis_event_service/populator.py`

### PR DESCRIPTION
**Pull request by damonkelley**
Resolves #19.

### CODE REVIEW

**Comment by damonkelley** [comment]
ping @ldko @somexpert

**Comment by vphill** [comment]
:+1:

**Comment by somexpert** [comment]
I'll take your word for it that none of this is used. :+1:

**Comment by damonkelley** [comment]
https://github.com/unt-libraries/django-premis-event-service/search?utf8=%E2%9C%93&q=populator
https://github.com/unt-libraries/django-premis-event-service/search?utf8=%E2%9C%93&q=helpy

If you follow those, you will see that no other module imports them. You *will* see that the docs reference them, but we are going to have to do a full overhaul of the docs in the near future, so I am not worried about that right now.

**Comment by damonkelley** [comment]
Also Resolves #12

**Comment by somexpert** [comment]
Alright, works for me. They aren't used.

**Comment by ldko** [comment]
Goodbye, helpy. :+1:

**Pull request merged**
